version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
    - --config=/etc/otel-collector-config.yaml
    volumes:
    - otel_workspace/config/collector.yaml:/etc/otel-collector-config.yaml
    - otel_workspace/traces:/var/log/swarmsh
    ports:
    - 4317:4317
    - 4318:4318
    - 8889:8889
    - 13133:13133
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - 16686:16686
    - 14250:14250
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
  prometheus:
    image: prom/prometheus:latest
    volumes:
    - otel_workspace/config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
